-- =====================================================================
-- SHARE2INSPIRE - COACH AGENT DATABASE SETUP
-- Supabase table for logging coach agent conversations
-- 
-- Created: 2026-01-14
-- Purpose: Store and analyze coach agent interactions
-- =====================================================================

-- Create coach_conversations table
CREATE TABLE IF NOT EXISTS public.coach_conversations (
    id BIGSERIAL PRIMARY KEY,
    session_id TEXT NOT NULL,
    user_message TEXT NOT NULL,
    bot_response TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    page_url TEXT,
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_coach_conversations_session_id 
ON public.coach_conversations(session_id);

CREATE INDEX IF NOT EXISTS idx_coach_conversations_timestamp 
ON public.coach_conversations(timestamp DESC);

-- Enable Row Level Security (RLS)
ALTER TABLE public.coach_conversations ENABLE ROW LEVEL SECURITY;

-- Create policy to allow anonymous inserts (for logging)
CREATE POLICY "Allow anonymous inserts" 
ON public.coach_conversations
FOR INSERT 
TO anon
WITH CHECK (true);

-- Create policy to allow authenticated reads
CREATE POLICY "Allow authenticated reads" 
ON public.coach_conversations
FOR SELECT 
TO authenticated
USING (true);

-- Add comments for documentation
COMMENT ON TABLE public.coach_conversations IS 
'Stores all conversations between users and the Coach AI agent for analytics and improvement';

COMMENT ON COLUMN public.coach_conversations.session_id IS 
'Unique session identifier to group conversations from the same user session';

COMMENT ON COLUMN public.coach_conversations.user_message IS 
'Message sent by the user';

COMMENT ON COLUMN public.coach_conversations.bot_response IS 
'Response generated by the Coach AI';

COMMENT ON COLUMN public.coach_conversations.page_url IS 
'URL of the page where the conversation occurred';

COMMENT ON COLUMN public.coach_conversations.user_agent IS 
'Browser user agent string for analytics';

-- =====================================================================
-- ANALYTICS VIEWS
-- =====================================================================

-- View for conversation statistics
CREATE OR REPLACE VIEW public.coach_conversation_stats AS
SELECT 
    DATE(timestamp) as conversation_date,
    COUNT(DISTINCT session_id) as unique_sessions,
    COUNT(*) as total_messages,
    COUNT(*) / COUNT(DISTINCT session_id) as avg_messages_per_session
FROM public.coach_conversations
GROUP BY DATE(timestamp)
ORDER BY conversation_date DESC;

-- View for popular topics (based on keywords)
CREATE OR REPLACE VIEW public.coach_popular_topics AS
SELECT 
    CASE 
        WHEN LOWER(user_message) LIKE '%coaching%' OR LOWER(user_message) LIKE '%sessão%' THEN 'Coaching'
        WHEN LOWER(user_message) LIKE '%cv%' OR LOWER(user_message) LIKE '%currículo%' THEN 'Análise CV'
        WHEN LOWER(user_message) LIKE '%serviço%' OR LOWER(user_message) LIKE '%oferta%' THEN 'Serviços'
        WHEN LOWER(user_message) LIKE '%preço%' OR LOWER(user_message) LIKE '%valor%' THEN 'Preços'
        WHEN LOWER(user_message) LIKE '%contacto%' OR LOWER(user_message) LIKE '%email%' THEN 'Contacto'
        ELSE 'Outros'
    END as topic,
    COUNT(*) as message_count,
    COUNT(DISTINCT session_id) as unique_sessions
FROM public.coach_conversations
WHERE timestamp > NOW() - INTERVAL '30 days'
GROUP BY topic
ORDER BY message_count DESC;

-- Grant access to views
GRANT SELECT ON public.coach_conversation_stats TO authenticated;
GRANT SELECT ON public.coach_popular_topics TO authenticated;

-- =====================================================================
-- SAMPLE QUERIES FOR ANALYTICS
-- =====================================================================

-- Get recent conversations
-- SELECT * FROM coach_conversations 
-- ORDER BY timestamp DESC 
-- LIMIT 50;

-- Get conversation by session
-- SELECT * FROM coach_conversations 
-- WHERE session_id = 'session_xxx' 
-- ORDER BY timestamp ASC;

-- Get daily statistics
-- SELECT * FROM coach_conversation_stats 
-- WHERE conversation_date > CURRENT_DATE - INTERVAL '7 days';

-- Get popular topics
-- SELECT * FROM coach_popular_topics;

-- =====================================================================
-- MAINTENANCE
-- =====================================================================

-- Function to clean old conversations (optional, run manually)
-- Keeps last 90 days of data
CREATE OR REPLACE FUNCTION clean_old_coach_conversations()
RETURNS INTEGER AS $$
DECLARE
    deleted_count INTEGER;
BEGIN
    DELETE FROM public.coach_conversations
    WHERE timestamp < NOW() - INTERVAL '90 days';
    
    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    RETURN deleted_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant execute permission to authenticated users
GRANT EXECUTE ON FUNCTION clean_old_coach_conversations() TO authenticated;

COMMENT ON FUNCTION clean_old_coach_conversations() IS 
'Deletes coach conversation records older than 90 days. Returns number of deleted records.';
