export {
  MENU_PAGE_IDS,
  SERVICE_PAGE_IDS,
  routeManifest,
  normalizePath,
  splitPathSegments,
  getLocaleFromPath,
  stripLocalePrefix,
  getRouteDefinition,
  resolveRoute,
  resolvePageId,
  getLocalizedPath,
  getCanonicalPtPath,
  switchPathToLang,
  getMenuItems,
  getLanguageOptions,
  getLanguageLinks,
  normalizeActivePage,
  getMenuLabels,
  type PageId,
  type RouteGroup,
  type LocalizedRoute,
  type RouteDefinition,
  type ResolvedRoute,
} from './routeManifest';
